title: "ddj82 블로그"
author: GitHub User
email: "azmzm@naver.com"
description: "개발과 공부를 기록하는 블로그입니다."
show_excerpts: true

sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: 김동준
  tagline: 개발자 지망생
  date_format: "%Y-%m-%d"
  style: black
  showNav: false
  showPicker: true

  social_links:
    github:  ddj82


header_pages:
  - about.md

remote_theme: samarsault/texture

plugins:
  - jekyll-remote-theme